### ISSUE TITLE
Blanks in entries

### ISSUE THREAD

**Issue by behzadipour** [fsesterh/THK_CrsGrp_Enrollment#1]
Hello,
we have noticed that during import there is an error message if the csv file contains spaces before/after the entries (e.g. userid). 
It would be useful if there was a possibility to check or automatically remove the blanks.
regards
Mojdeh

**Comment by fsesterh** [comment]
This has been fixed with https://github.com/fsesterh/THK_CrsGrp_Enrollment/commit/05ae1d95d14347f4bf9788f4b5eb8b289e0dcaab

Please update via git pull.

Blanks are now trimmed from all rows.
