### ISSUE TITLE
Update for ILIAS 8 planned?

### ISSUE THREAD

**Issue by rfcmaXi** [fsesterh/THK_CrsGrp_Enrollment#2]
Hello,
We use this plugin partly for manual course assignments. 
Everyone is talking about it at the moment: Will there be an update for ILIAS 8?
Greetings and thank you!!!!

**Comment by fsesterh** [comment]
Hi,
we are in the testing phase for it ourselves. I've published / pushed the plugin version for ILIAS 8. Branch: r8_develop. Please note that with the update to ILIAS 8 the  plugins no longer works with the background tasks. Instead the plugin adds a cron task to the global cron job for ILIAS. The time it takes until an import is processed then depends on when you run the cron job server-side.
Regards,
Fabian
