### ISSUE TITLE
Class "ILIAS\Plugin\CrsGrpImport\Utils\UiUtil" not found

### ISSUE THREAD

**Issue by rfcmaXi** [fsesterh/THK_CrsGrp_Enrollment#3]
Hello,
after installing the dev branch for ILIAS_8 I get the following message when calling the function in the course. I think that should not be called >CrsGrpImport< :)
Thanks!!!

Error thrown with message "Class "ILIAS\Plugin\CrsGrpImport\Utils\UiUtil" not found"

Stacktrace:
#9 Error in /Applications/MAMP/htdocs/ILIAS8/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CrsGrpEnrollment/classes/Frontend/Controller/CourseGroupEnrollment.php:73
#8 ILIAS\Plugin\CrsGrpEnrollment\Frontend\Controller\CourseGroupEnrollment:init in /Applications/MAMP/htdocs/ILIAS8/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CrsGrpEnrollment/classes/Frontend/Controller/Base.php:70
#7 ILIAS\Plugin\CrsGrpEnrollment\Frontend\Controller\Base:__construct in /Applications/MAMP/htdocs/ILIAS8/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CrsGrpEnrollment/classes/Frontend/Dispatcher.php:86
#6 ILIAS\Plugin\CrsGrpEnrollment\Frontend\Dispatcher:instantiateController in /Applications/MAMP/htdocs/ILIAS8/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CrsGrpEnrollment/classes/Frontend/Dispatcher.php:53
#5 ILIAS\Plugin\CrsGrpEnrollment\Frontend\Dispatcher:dispatch in /Applications/MAMP/htdocs/ILIAS8/Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CrsGrpEnrollment/classes/class.ilCrsGrpEnrollmentUIHookGUI.php:45
#4 ilCrsGrpEnrollmentUIHookGUI:executeCommand in /Applications/MAMP/htdocs/ILIAS8/Services/UICore/classes/class.ilCtrl.php:199
#3 ilCtrl:forwardCommand in /Applications/MAMP/htdocs/ILIAS8/Services/UIComponent/classes/class.ilUIPluginRouterGUI.php:48
#2 ilUIPluginRouterGUI:executeCommand in /Applications/MAMP/htdocs/ILIAS8/Services/UICore/classes/class.ilCtrl.php:199
#1 ilCtrl:forwardCommand in /Applications/MAMP/htdocs/ILIAS8/Services/UICore/classes/class.ilCtrl.php:174
#0 ilCtrl:callBaseClass in /Applications/MAMP/htdocs/ilias8/ilias.php:24

**Comment by fsesterh** [comment]
Fixed in git: 1fec3e7bd1fc05863bb12791eb0ea9e59d70fe55
